name: Release

on:
  workflow_dispatch:
permissions: write-all

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and export
      run: |
        make windows CC=x86_64-w64-mingw32-gcc
    - name: Release
      uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: |
          *
        name: ByeDPI
        tag: download
        body: Download Below
