name: Release

on:
  workflow_dispatch:
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build and export
      run: |
        make
    - name: Release
      uses: softprops/action-gh-release@v0.1.15
      with:
        files: |
          ./
        name: Download
        tag_name: all
        body: Download Here
